[tox]
envlist = {py37, py38, py39}-django{32}

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = testauth.settings

deps=
    django32: allianceauth<3
    aa-memberaudit>=1.15.2
    coverage
    factory_boy

commands=
    coverage run runtests.py inactivity -v 2
    coverage xml
    coverage report
